export const fake_data = [
  {
    id: 1,
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
  {
    id: 2,
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
  {
    id: 3,
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
  {
    id: 4,
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
  {
    id: 5,
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
  {
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
  {
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
  {
    directions: [
      "Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes.",
      "Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments.",
      "*Available at Asian markets and many supermarkets.",
    ],
    ingredients: [
      "1/4 cup soy sauce",
      "1 tablespoon sugar",
      "2 teaspoons Asian sesame oil",
      "1 bunch scallions (white and pale green parts separated from greens), minced (1/2 cup)",
    ],
    title: "Korean Marinated Beef",
    image_url:
      "https://assets.epicurious.com/photos/560df200f3a00aeb2f1d5bf8/109206.jpg",
    description: "Bulgogi",
    calories: 170,
    rating: 4.5,
    fat: 10,
  },
];

export const DropdownFake = [
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
  {
    name: "Dish Type",
    values: [
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
      "Healthy",
      "Chicken",
      "Lunch",
      "Quick&Easy",
      "Summer",
      "Dinner",
    ],
  },
];
