# Generated by Django 3.1.7 on 2021-04-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recipe_id',
            field=models.TextField(),
        ),
    ]
